name: pydra-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - git-annex
  - datalad
  - pip
  - pip:
    - pydra
    - jupyter
    - jupyter_contrib_nbextensions
    - jupytext
    - jupyterlab
    - matplotlib
    - nbformat
    - nbval
    - nest_asyncio
    - psutil
    - pytest
    - numpy
    - pandas
    - scipy
    - nibabel
    - nilearn
